### ISSUE TITLE
Conflict with Bootstrap grid classes

### ISSUE THREAD

**Issue by diegoaguilar** [brandly/angular-youtube-embed#76]
I'm trying following markup:

```jade
.row(ng-show='currentVideoId')
  .col-md-6
      youtube-video(video-id='currentVideoId')
  .col-md-6
    form.well.text-center(ng-controller='RecordController')
      .form-group
        label Inicio
        br
        button.btn.btn-success Inicio
      .form-group
        label Fin
        br
        button.btn.btn-warning Fin     
```

The problem is the video frame's coulum is getting overlapped against the continous column:

![image](https://cloud.githubusercontent.com/assets/2483678/10320654/30cb1408-6c3a-11e5-9f3f-fe13aedc60b7.png)

Then I tried adding the embedded classes:

```jade
    .embed-responsive
      youtube-video(video-id='currentVideoId').embed-responsive-item
```

And then the iframe gets hidden:

![image](https://cloud.githubusercontent.com/assets/2483678/10320739/97487b8a-6c3a-11e5-9d1b-b1bc437e79eb.png)

I tried also to include manually the classes even I'm already using Bootstrap but got not results. These are the classes I included:

```css
.embed-responsive {
  position: relative;
  display: block;
  height: 0;
  padding: 0;
  overflow: hidden;
}

.embed-responsive.embed-responsive-16by9 {
  padding-bottom: 56.25%;
}

.embed-responsive-item {
  position: absolute;
  top: 0;
  bottom: 0;
  left: 0;
  width: 100%;
  height: 100%;
  border: 0;
}
```
